const KEY="technical-doc-builder-standalone-v1";
const makeSection=()=>({id:Date.now()+Math.random(),heading:"New Technology",subheading:"Overview",bullets:["Add a key technical point"],code:"// Add example code here\nconsole.log('Hello technology');",preview:"Expected output:\nHello technology"});
let state={title:"New Technologies - Technical Document",summary:"A practical technical reference with concepts, implementation notes, examples, and expected output.",sections:[makeSection()]};
try{const x=JSON.parse(localStorage.getItem(KEY));if(x)state=x}catch(e){}
const $=x=>document.getElementById(x); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('status').textContent='• Saved locally';setTimeout(()=>$('status').textContent='',900)}
function render(){ $('title').value=state.title;$('summary').value=state.summary;$('pTitle').textContent=state.title;$('pSummary').textContent=state.summary;
$('sectionEditors').innerHTML=state.sections.map((s,i)=>`<div class="card sectionEditor"><b>Section ${i+1}</b> <button class="btn" style="float:right" onclick="removeSection(${i})">Delete</button><div class="label">Heading</div><input class="field" value="${esc(s.heading)}" oninput="setField(${i},'heading',this.value)"><div class="label">Subheading</div><input class="field" value="${esc(s.subheading)}" oninput="setField(${i},'subheading',this.value)"><div class="label">Bullet points</div>${s.bullets.map((b,j)=>`<div class="row"><input class="field" value="${esc(b)}" oninput="setBullet(${i},${j},this.value)"><button class="btn" onclick="removeBullet(${i},${j})">×</button></div>`).join('')}<button class="btn" onclick="addBullet(${i})">+ Bullet</button><div class="label" style="margin-top:10px">Example code</div><textarea class="field" rows="6" oninput="setField(${i},'code',this.value)">${esc(s.code)}</textarea><div class="label">Code preview / output</div><textarea class="field" rows="4" oninput="setField(${i},'preview',this.value)">${esc(s.preview)}</textarea></div>`).join('');
$('preview').innerHTML=state.sections.map((s,i)=>`<section class="docSection"><h2>${i+1}. ${esc(s.heading)}</h2><h3>${esc(s.subheading)}</h3><ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><b>Example code</b><pre class="code">${esc(s.code)}</pre><b>Preview / expected output</b><pre class="output">${esc(s.preview)}</pre></section>`).join('');save()}
function setField(i,k,v){state.sections[i][k]=v;renderPreviewOnly()} function setBullet(i,j,v){state.sections[i].bullets[j]=v;renderPreviewOnly()}function addBullet(i){state.sections[i].bullets.push('New point');render()}function removeBullet(i,j){state.sections[i].bullets.splice(j,1);render()}function removeSection(i){if(state.sections.length>1){state.sections.splice(i,1);render()}}function renderPreviewOnly(){state.title=$('title').value;state.summary=$('summary').value;$('pTitle').textContent=state.title;$('pSummary').textContent=state.summary;$('preview').innerHTML=state.sections.map((s,i)=>`<section class="docSection"><h2>${i+1}. ${esc(s.heading)}</h2><h3>${esc(s.subheading)}</h3><ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><b>Example code</b><pre class="code">${esc(s.code)}</pre><b>Preview / expected output</b><pre class="output">${esc(s.preview)}</pre></section>`).join('');save()}
$('title').oninput=renderPreviewOnly;$('summary').oninput=renderPreviewOnly;$('addSection').onclick=()=>{state.sections.push(makeSection());render()};$('previewBtn').onclick=()=>{$('editor').classList.toggle('hidden');$('layout').style.gridTemplateColumns=$('editor').classList.contains('hidden')?'1fr':''};render();